from enum import Enum


class ValidationOutcome(str, Enum):
    VALID = "valid"
    INVALID = "invalid"
    QUARANTINED = "quarantined"
    INDETERMINATE = "indeterminate"


class ErrorCode(str, Enum):
    PARSE = "AEGIS_E_PARSE"
    CANONICALIZATION = "AEGIS_E_CANONICALIZATION"
    DIGEST_MISMATCH = "AEGIS_E_DIGEST_MISMATCH"
    SIGNATURE_INVALID = "AEGIS_E_SIGNATURE_INVALID"
    IDENTITY_UNRESOLVED = "AEGIS_E_IDENTITY_UNRESOLVED"
    INTENT_SCOPE_DENIED = "AEGIS_E_INTENT_SCOPE_DENIED"
    RUNTIME_ATTESTATION_STALE = "AEGIS_E_RUNTIME_ATTESTATION_STALE"
    PROVENANCE_GAP = "AEGIS_E_PROVENANCE_GAP"
    IMPACT_UNREVIEWED = "AEGIS_E_IMPACT_UNREVIEWED"
    REGISTRY_UNAVAILABLE = "AEGIS_E_REGISTRY_UNAVAILABLE"
    REQUIRED_FIELD = "AEGIS_E_REQUIRED_FIELD"
    TYPE = "AEGIS_E_TYPE"
    IDENTIFIER = "AEGIS_E_IDENTIFIER"
